version: '3.8'

services:
  mongo:
    image: mongo:7.0  
    container_name: local-mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
