name: Continuous Integration

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  # Validate if the branch is allowed to be merged or not
  validate-branches:
    name: "Validate Branch Rules"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: "Check Main -> Production Merge"
        if: github.base_ref == 'production' && github.head_ref != 'main'
        run: |
          echo "❌ ERRO: Pull requests para 'production' só podem ser feitos a partir da branch 'main'."
          echo "Este PR está vindo da branch '${{ github.head_ref }}', o que não é permitido."
          exit 1

      - name: "Block Production -> Main Merge"
        if: github.base_ref == 'main' && github.head_ref == 'production'
        run: |
          echo "❌ ERRO: A branch 'production' não pode ser mesclada de volta na 'main'."
          echo "Hotfixes devem ser feitos em uma branch separada e mesclados tanto em 'main' quanto em 'production'."
          exit 1

      - name: "Approve valid merge"
        if: (github.base_ref == 'production' && github.head_ref == 'main') || (github.base_ref == 'main' && github.head_ref != 'production')
        run: echo "Tudo correto, pode prosseguir!"

  build:
    name: "Build Application"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Prisma client
        run: bunx prisma generate --schema=src/infra/database/prisma/schema.prisma

      - name: Build application
        run: bun run build

  type-check:
    name: "Type Check"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Type Check
        run: bun run type-check
