name: Production Deployment

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: production
    secrets: inherit
